server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/heroku?useSSL=false
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
